### ISSUE TITLE
Request does not match any route.

### ISSUE THREAD

**Issue by rbc90** [troublediehard/mma-customapi#1]
{
    "message": "Request does not match any route.",
    "trace": null
}

Hey, I'm getting above mentioned error. Can you please help me?

**Comment by dimaportenko** [comment]
@rbc90 sure, please 
1) share request you are trying to use 
2) have you done following commands
php bin/magento setup:upgrade
php bin/magento cache:clean

**Comment by rbc90** [comment]
I'm sorry! It was my fault. I have declared an incorrect module name. Thanks! It is working now. Can I get full URL instead of just image name?

**Comment by dimaportenko** [comment]
You can do it on Magento side - add URL path in https://github.com/troublediehard/mma-customapi/blob/master/Model/Category/Tree.php on line 139

Or you can get media URL via rest like 
GET /V1/store/storeConfigs

**Comment by rbc90** [comment]
@troublediehard Thanks! for the help (y)
