### ISSUE TITLE
Installation instructions do not work

### ISSUE THREAD

**Issue by KeenanLawrence** [troublediehard/mma-customapi#2]
Hi @troublediehard ,
I don't know if I'm missing something (not a PHP Dev and have minimal experience with Magento), but the installation instructions do not work.

The following error is thrown when running `php bin/magento setup:upgrade`:

```
Autoload error: 
Module 'MMA_CustomApi' from '/var/www/html/app/code/MMA/CustomApi' has been already defined in '/var/www/html/vendor/mma/customapi'
```

Removing the folder in `<installation_dir>/app/code/MMA/`, the `php bin/magento setup:upgrade` command succeeds (and subsequent cache:clean command).

However, if I try to re-compile using `php bin/magento setup:di:compile`, it fails with the below error:

```
Compilation was started.

Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 58.0 MiB

PHP Fatal error:  Interface 'Cor\Rest\Api\PaymentTokenManagementInterface' not found in /var/www/html/vendor/mma/customapi/Model/PaymentTokenManagement.php on line 25
```

Is this something to be concerned about or is this not yet compatible with Magento 2.2.8 (was advised to upgrade from 2.2.6 due to security concerns)?

---
(Relevant) Environment details:
```
PHP version: 7.0.33
Magento version: 2.2.8
Composer version: 1.8.5
```

**Comment by dimaportenko** [comment]
@KeenanLawrence
I don't really have time to add fix right now, but you can try 
```
in  
Model/PaymentTokenManagement.php
replace 
\Cor\Rest\Api\PaymentTokenManagementInterface
with 
\MMA\CustomApi\Api\PaymentTokenManagementInterface
```

**Comment by KeenanLawrence** [comment]
@troublediehard 
Thanks, the fix worked.

I've created a [PR](https://github.com/troublediehard/mma-customapi/pull/3)
