### ISSUE TITLE
The consumer isn't authorized to access %resources.

### ISSUE THREAD

**Issue by amankkcc** [troublediehard/mma-customapi#4]
I'm getting this error on every API endpoint of this REST API extension even when I'm adding the bearer token for customer.

**Comment by amankkcc** [comment]
With admin baerer token it's giving the data. Can we make it open for guest users ?

**Comment by dimaportenko** [comment]
@amankkcc yes, you need to modify https://github.com/troublediehard/mma-customapi/blob/master/etc/webapi.xml resources tag, set it like this
```
<resources>
    <resource ref="anonymous"/>
</resources>
```

**Comment by amankkcc** [comment]
Thank you so much, I got it figured out. You just saved my day by creating this REST API extension.

**Comment by dimaportenko** [comment]
@amankkcc welcome!
